# More on tensor

In [1]:
import torch

In [3]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.7896, 0.7254, 0.8794],
        [0.6844, 0.6000, 0.7662]])
tensor([[0.3674, 0.4501, 0.6444],
        [0.6683, 0.6712, 0.3849]])


In [4]:
# comparison
print(torch.eq(a, b)) # return a tensor containing the result when the corresponding elements are equal or not
print(torch.equal(a, b)) # return true/false when size and elements are equal

print(torch.ge(a, b)) # greater or equal matrix results
print(torch.gt(a, b)) # greater matrix results
print(torch.le(a, b)) # less or equal matrix results
print(torch.lt(a, b)) # less matrix results

tensor([[False, False, False],
        [False, False, False]])
False
tensor([[ True,  True,  True],
        [ True, False,  True]])
tensor([[ True,  True,  True],
        [ True, False,  True]])
tensor([[False, False, False],
        [False,  True, False]])
tensor([[False, False, False],
        [False,  True, False]])


In [10]:
# sort
a = torch.tensor([[1, 4, 4, 3, 5], [2, 3, 1, 3, 5]])
print(a.shape)
print(torch.sort(a, dim=0, descending=True)) # sort based on first dimension (2 in this case)
print(torch.sort(a, dim=1, descending=True)) # sort based on second dimension (5 in this case)

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[2, 4, 4, 3, 5],
        [1, 3, 1, 3, 5]]),
indices=tensor([[1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1]]))
torch.return_types.sort(
values=tensor([[5, 4, 4, 3, 1],
        [5, 3, 3, 2, 1]]),
indices=tensor([[4, 1, 2, 3, 0],
        [4, 1, 3, 0, 2]]))


In [17]:
# topk
a = torch.tensor([[1, 4, 4, 3, 5], [2, 3, 1, 3, 5]])
print(a.shape)
print(torch.topk(a, k=2, dim=1)) # choose the top k element based on first dimension
print(torch.kthvalue(a, k=2, dim=1)) # choose the kth smallest element based on first dimension

torch.Size([2, 5])
torch.return_types.topk(
values=tensor([[5, 4],
        [5, 3]]),
indices=tensor([[4, 2],
        [4, 1]]))
torch.return_types.kthvalue(
values=tensor([3, 2]),
indices=tensor([3, 0]))


In [20]:
a = torch.rand(2, 3)
print(a)
print(torch.isfinite(a)) # whether element is finite or not matrix results
print(torch.isfinite(a / 0))
print(torch.isinf(a)) # whether element is infinite or not matrix results
print(torch.isinf(a / 0))

import numpy as np
a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))

tensor([[0.1274, 0.0803, 0.9278],
        [0.7464, 0.2242, 0.4744]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([False, False,  True])


In [22]:
# Trigonometric functions
# others are similarly implemented
a = torch.ones(2, 3)
b = torch.cos(a) # use radian
print(b)

tensor([[0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403]])
