# More on tensor

In [2]:
import torch

In [ ]:
# filling
print(torch.full((2, 3), 10)) # return a tensor with specified size with all values the same as specified

tensor([[10, 10, 10],
        [10, 10, 10]])


In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.8607, 0.1650, 0.0761],
        [0.4414, 0.4125, 0.1067]])
tensor([[0.3383, 0.5160, 0.5152],
        [0.6667, 0.2797, 0.9541]])


In [ ]:
# comparison
print(torch.eq(a, b)) # return a tensor containing the result when the corresponding elements are equal or not
print(torch.equal(a, b)) # return true/false when size and elements are equal

print(torch.ge(a, b)) # greater or equal matrix results
print(torch.gt(a, b)) # greater matrix results
print(torch.le(a, b)) # less or equal matrix results
print(torch.lt(a, b)) # less matrix results

tensor([[False, False, False],
        [False, False, False]])
False
tensor([[ True, False, False],
        [False,  True, False]])
tensor([[ True, False, False],
        [False,  True, False]])
tensor([[False,  True,  True],
        [ True, False,  True]])
tensor([[False,  True,  True],
        [ True, False,  True]])


In [ ]:
# sort
a = torch.tensor([[1, 4, 4, 3, 5], [2, 3, 1, 3, 5]])
print(a.shape)
print(torch.sort(a, dim=0, descending=True)) # sort based on first dimension (2 in this case)
print(torch.sort(a, dim=1, descending=True)) # sort based on second dimension (5 in this case)

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[2, 4, 4, 3, 5],
        [1, 3, 1, 3, 5]]),
indices=tensor([[1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1]]))
torch.return_types.sort(
values=tensor([[5, 4, 4, 3, 1],
        [5, 3, 3, 2, 1]]),
indices=tensor([[4, 1, 2, 3, 0],
        [4, 1, 3, 0, 2]]))


In [ ]:
# topk
a = torch.tensor([[1, 4, 4, 3, 5], [2, 3, 1, 3, 5]])
print(a.shape)
print(torch.topk(a, k=2, dim=1)) # choose the top k element based on first dimension
print(torch.kthvalue(a, k=2, dim=1)) # choose the kth smallest element based on first dimension

torch.Size([2, 5])
torch.return_types.topk(
values=tensor([[5, 4],
        [5, 3]]),
indices=tensor([[4, 2],
        [4, 1]]))
torch.return_types.kthvalue(
values=tensor([3, 2]),
indices=tensor([3, 0]))


In [ ]:
a = torch.rand(2, 3)
print(a)
print(torch.isfinite(a)) # whether element is finite or not matrix results
print(torch.isfinite(a / 0))
print(torch.isinf(a)) # whether element is infinite or not matrix results
print(torch.isinf(a / 0))

import numpy as np
a = torch.tensor([1, 2, np.nan])
print(torch.isnan(a))

tensor([[0.4206, 0.9986, 0.3235],
        [0.8078, 0.8544, 0.1996]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([False, False,  True])


In [ ]:
# Trigonometric functions
# others are similarly implemented
a = torch.ones(2, 3)
b = torch.cos(a) # use radian
print(b)

tensor([[0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403]])


In [ ]:
# statistic
a = torch.rand(2, 2)
print(a)
print(torch.mean(a, dim=0))
print(torch.sum(a, dim=0))
print(torch.prod(a, dim=0))

tensor([[0.2056, 0.1908],
        [0.6588, 0.0880]])
tensor([0.4322, 0.1394])
tensor([0.8644, 0.2788])
tensor([0.1354, 0.0168])


In [ ]:
print(torch.argmax(a, dim=0)) # return the index of max element
print(torch.argmin(a, dim=0)) # return the index of min element

tensor([1, 0])
tensor([0, 1])


In [ ]:
print(torch.std(a))
print(torch.var(a))
# return a tuple that contains the mode value of each row
print(torch.mode(a)) # by default, dim is the last dimension of input tensor
print(torch.median(a)) # when there are even number of elements, the lower one is returned

tensor(0.2541)
tensor(0.0646)
torch.return_types.mode(
values=tensor([0.1908, 0.0880]),
indices=tensor([1, 1]))
tensor(0.1908)


In [ ]:
a = torch.rand(2, 2) * 10
print(a)
print(torch.histc(a, 6, 0, 0)) # 6 is the number of bin, and first 0 is the min and second 0 is the max
# this will divides the data according to the min and max into 6 intervals
# and calculate the frequency of elements occured in each interval

tensor([[2.7497, 2.2534],
        [8.6642, 0.7916]])
tensor([1., 2., 0., 0., 0., 1.])


In [ ]:
a = torch.randint(0, 10, [10])
print(a)
# bincount only works for one dimensional tensor
print(torch.bincount(a)) # count the frequency of certain values from min up to max

tensor([0, 2, 5, 5, 8, 5, 3, 9, 0, 8])
tensor([2, 0, 1, 1, 0, 3, 0, 0, 2, 1])


In [ ]:
# random sampling
torch.manual_seed(1) # seed allows the result of random sampling the same
mean = torch.rand(1, 2)
std = torch.rand(1, 2)
print(torch.normal(mean, std))

tensor([[0.7825, 0.7358]])


In [ ]:
# norm
a = torch.rand(2, 1)
b = torch.rand(2, 1)

print(a, b)
# p indicates p-norm
print(torch.dist(a, b, p=1))
print(torch.dist(a, b, p=2))
print(torch.dist(a, b, p=3))

print(torch.norm(a))
print(torch.norm(a, p='nuc')) # nuclear norm: the sum of singular values of matrix

tensor([[0.3801],
        [0.8335]]) tensor([[0.0241],
        [0.1804]])
tensor(1.0091)
tensor(0.7438)
tensor(0.6866)
tensor(0.9160)
tensor(0.9160)


**EVD and SVD**
*   **EVD** requires matrix to be a **square matrix that can be diagonalized**
*   Otherwise use **SVD**

**Note**: **EVD** is usually used in **PCA** and **SVD** is usually used in **LDA**

In [ ]:
a = torch.rand(2, 2)
print(a)
print(torch.svd(a))

tensor([[0.3840, 0.3865],
        [0.1294, 0.9257]])
torch.return_types.svd(
U=tensor([[ 0.4595,  0.8882],
        [ 0.8882, -0.4595]]),
S=tensor([1.0413, 0.2934]),
V=tensor([[ 0.2798,  0.9601],
        [ 0.9601, -0.2798]]))


In [ ]:
# clamp
a = torch.rand(2, 2) * 10

print(a)
print(a.clamp(1, 5)) # clamps all elements within the range of [min, max]
# if < min, it becomes min
# if in range, it stay the same
# if > max, it becomes max

tensor([[2.8025, 0.5520],
        [8.3784, 9.1201]])
tensor([[2.8025, 1.0000],
        [5.0000, 5.0000]])


## Select index

In [ ]:
# where
a = torch.rand(4, 4)
b = torch.rand(4, 4)
print(a, b)
print(torch.where(a > 0.5, a, b)) # this indicates if condition meets, select value from a, if not select from b
print(torch.where(a > 0.5, 1, 0))

tensor([[0.6078, 0.4620, 0.4779, 0.8932],
        [0.4591, 0.3480, 0.4206, 0.7170],
        [0.5932, 0.6879, 0.4112, 0.2192],
        [0.4737, 0.4612, 0.4602, 0.7939]]) tensor([[0.2604, 0.5633, 0.7384, 0.2772],
        [0.1376, 0.1312, 0.0582, 0.9682],
        [0.4332, 0.0817, 0.7359, 0.8397],
        [0.2989, 0.6279, 0.9523, 0.5173]])
tensor([[0.6078, 0.5633, 0.7384, 0.8932],
        [0.1376, 0.1312, 0.0582, 0.7170],
        [0.5932, 0.6879, 0.7359, 0.8397],
        [0.2989, 0.6279, 0.9523, 0.7939]])
tensor([[1, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 1, 0, 0],
        [0, 0, 0, 1]])


In [ ]:
# index_select
a = torch.rand(4, 4)
print(a)
print(torch.index_select(a, dim=0, index=torch.tensor([0, 3, 2]))) # this forms new tensor by indexing the tensor along dimension dim using entries in index
# Note: the dimth dimension of new tensor will be the length of index while others the same

tensor([[0.7096, 0.1972, 0.1624, 0.5510],
        [0.3343, 0.6830, 0.1136, 0.6127],
        [0.4899, 0.0715, 0.2985, 0.2726],
        [0.0579, 0.7922, 0.1330, 0.7353]])
tensor([[0.7096, 0.1972, 0.1624, 0.5510],
        [0.0579, 0.7922, 0.1330, 0.7353],
        [0.4899, 0.0715, 0.2985, 0.2726]])


In [ ]:
# gather
a = torch.linspace(1, 16, 16).view(4, 4)
print(a)
# Note: the result matrix is the size of index and index size need to be less than or equal to the original size
# Note; each value is retrieved from the each index on that dim
print(torch.gather(a, dim=0, index=torch.tensor([[0, 1, 1, 1], [0, 1, 2, 3]]))) # gather values along dimension dim

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 16.]])


In [ ]:
# mask
print(a)
print(torch.masked_select(a, torch.gt(a, 8))) # return a 1D tensor according to the condition mask where mask is the BoolTensor

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])


In [ ]:
# take
print(a)
print(torch.take(a, index=torch.tensor([0, 15, 13, 10]))) # take will treat the original tensor as 1D tensor and return 1D tensor with values of specified index

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([ 1., 16., 14., 11.])


In [ ]:
# nonzero
a = torch.tensor([[0, 1, 0, 4, 0], [0, 2, 0, 0, 1]])
print(torch.nonzero(a)) # return the index of nonzero element in tensor

tensor([[0, 1],
        [0, 3],
        [1, 1],
        [1, 4]])


## Concatenation

In [ ]:
# cat
a = torch.zeros(2, 4)
b = torch.ones(2, 4)

print(a)
print(b)
print(torch.cat((b, a), dim=0)) # concatenate tensors based on the dim dimension (order matters)
# Note: result tensor has the same dimension

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# stack
a = torch.linspace(1, 6, 6).view(2, 3)
b = torch.linspace(7, 12, 6).view(2, 3)

print(a)
print(b)
out = torch.stack((a, b), dim=0) # treat each tensor as individual and create a new tensor along the new dim
print(out)
print(out.shape)
print(out[0, :, :]) # output a
print(out[1, :, :]) # output b

out = torch.stack((a, b), dim=2)
print(out)
print(out.shape)
print(out[:, :, 0]) # output a
print(out[:, :, 1]) # output b

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])
torch.Size([2, 3, 2])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


## Split

In [ ]:
# chunk
a = torch.rand(3, 4)
print(a)
print(torch.chunk(a, 2, dim=0)) # split the tensor into 2 parts by averaging on dimension 0
# Note: if not evenly splitted, the last chunk will have fewer

tensor([[0.9353, 0.4099, 0.2694, 0.7450],
        [0.7569, 0.3640, 0.1514, 0.2409],
        [0.3668, 0.2894, 0.0685, 0.6162]])
(tensor([[0.9353, 0.4099, 0.2694, 0.7450],
        [0.7569, 0.3640, 0.1514, 0.2409]]), tensor([[0.3668, 0.2894, 0.0685, 0.6162]]))


In [ ]:
# split
print(a)
print(torch.split(a, 1, dim=0)) # split the tensor into several tensors while each tensor has size 1 of dimension dim
# Note: similarly, the last one will have fewer if not evenly

tensor([[0.9353, 0.4099, 0.2694, 0.7450],
        [0.7569, 0.3640, 0.1514, 0.2409],
        [0.3668, 0.2894, 0.0685, 0.6162]])
(tensor([[0.9353, 0.4099, 0.2694, 0.7450]]), tensor([[0.7569, 0.3640, 0.1514, 0.2409]]), tensor([[0.3668, 0.2894, 0.0685, 0.6162]]))


## Transformation

In [ ]:
a = torch.rand(2, 3)
print(a)
print(torch.reshape(a, (3, 2))) # reshape
print(torch.t(a)) # transpose
print(torch.transpose(a, 0, 1)) # tranpose between dimension 0 and 1

tensor([[0.8114, 0.7677, 0.7213],
        [0.0294, 0.1573, 0.2245]])
tensor([[0.8114, 0.7677],
        [0.7213, 0.0294],
        [0.1573, 0.2245]])
tensor([[0.8114, 0.0294],
        [0.7677, 0.1573],
        [0.7213, 0.2245]])


In [ ]:
a = torch.rand(1, 2, 3)
print(a)
print(torch.squeeze(a)) # remove dimension that has size 1
print(torch.unsqueeze(a, -1).shape) # add a new dimension of size 1 at last position

tensor([[[0.8171, 0.1096, 0.0651],
         [0.5236, 0.1637, 0.5457]]])
tensor([[0.8171, 0.1096, 0.0651],
        [0.5236, 0.1637, 0.5457]])
torch.Size([1, 2, 3, 1])


In [ ]:
print(torch.unbind(a, dim=2)) # remove specified dim

print(a)
print(torch.flip(a, dims=[1, 2])) # dims indicates collection of dim to flip

(tensor([[0.8171, 0.5236]]), tensor([[0.1096, 0.1637]]), tensor([[0.0651, 0.5457]]))
tensor([[[0.8171, 0.1096, 0.0651],
         [0.5236, 0.1637, 0.5457]]])
tensor([[[0.5457, 0.1637, 0.5236],
         [0.0651, 0.1096, 0.8171]]])


In [ ]:
a = torch.rand(2, 3)
print(a)

out = torch.rot90(a, 1) # rotate 90 degree k times clockwise if k is negative otherwise unclockwise
print(out)
print(out.shape)

tensor([[0.1227, 0.5848, 0.9070],
        [0.8227, 0.9918, 0.8017]])
tensor([[0.9070, 0.8017],
        [0.5848, 0.9918],
        [0.1227, 0.8227]])
torch.Size([3, 2])


## Other

In [6]:
import numpy as np
# numpy to tensor
a = np.zeros([2, 2])
print(torch.from_numpy(a))

# tensor to numpy
a = torch.rand(2, 2)
print(a.numpy())

# change the running device to GPU
a.to(torch.device("cuda"))
print(a)

# change the running devic to CPU
a.to(torch.device("cpu"))
print(a)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)
[[0.40484196 0.7480007 ]
 [0.77405477 0.8904056 ]]
tensor([[0.4048, 0.7480],
        [0.7741, 0.8904]])
tensor([[0.4048, 0.7480],
        [0.7741, 0.8904]])
